services:
  next:
    build:
      context: ./next
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./next:/app
    ports:
      - "3000:3000"
    command: bash -c "yarn dev"
  rails:
    build:
      context: ./rails
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
    volumes:
      - ./rails:/app
    ports:
      - "3001:3001"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: