FROM ruby:3.3.5

ARG USERNAME=piniki
ARG USER_UID=1000
ARG USER_GID=$USER_UID

WORKDIR /app

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN bundle install

COPY . /app

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

RUN groupadd --gid $USER_GID $USERNAME \
  && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
  && chown -R $USERNAME:$USERNAME /app

USER $USERNAME

EXPOSE 3001

CMD ["rails", "server", "-b", "0.0.0.0"]
